name: artiver
description: articles time saver

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  connectivity_plus: ^1.0.4
  cupertino_icons: ^1.0.2
  dio: 4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.0.9
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  internet_connection_checker: ^0.0.1+1
  intl: ^0.17.0
  mockito: ^5.0.10

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  test: ^1.16.8

flutter:
  uses-material-design: true
  generate: true

