name: flutter

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0


      - name: Install Dependencies
        working-directory: ./app
        run: flutter packages get

      - name: Format
        working-directory: ./app
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        working-directory: ./app
        run: flutter analyze lib

      - name: Run tests
        working-directory: ./app
        run: flutter test --no-pub --test-randomize-ordering-seed random